# Generated by Django 3.2.5 on 2023-02-06 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Entry Date'),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Entry Date'),
        ),
    ]
